{
  "name": "sales_1M_workflow",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "sales_data_1M_raw",
        "columns": [
          {
            "name": "CustomerID",
            "dataType": "string",
            "sourceColumn": "CustomerID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sales",
            "dataType": "string",
            "sourceColumn": "Sales",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product",
            "dataType": "string",
            "sourceColumn": "Product",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "OrderDate",
            "dataType": "string",
            "sourceColumn": "OrderDate",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "sales_data_1M_raw-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    __Source = (let",
                "    Source = SharePoint.Files(\"https://sorimtechnologies.sharepoint.com\", [ApiVersion = 15]),",
                "    MatchingFiles = Table.SelectRows(Source, each [Name] = \"sales_data_1M.csv\"),",
                "    FileContent = if Table.RowCount(MatchingFiles) = 0 then error \"File not found in SharePoint: sales_data_1M.csv\" else MatchingFiles{0}[Content],",
                "    CsvData = Csv.Document(FileContent, [Delimiter = \",\", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(CsvData, [PromoteAllScalars = true]),",
                "    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, List.Transform(Table.ColumnNames(PromotedHeaders), each {_, type text}))",
                "in",
                "    ChangedTypes),",
                "    __BimColumns = {\"CustomerID\", \"Region\", \"Sales\", \"Product\", \"OrderDate\"},",
                "    __SafeBase = try",
                "        __Source",
                "    otherwise",
                "        Table.FromRecords({{}}, __BimColumns),",
                "    __AvailableColumns = List.Intersect({{Table.ColumnNames(__SafeBase), __BimColumns}}, MissingField.Error),",
                "    __WithMissingColumns = List.Accumulate(",
                "        List.Difference(__BimColumns, __AvailableColumns),",
                "        __SafeBase,",
                "        (tbl, col) => Table.AddColumn(tbl, col, each null, type any)",
                "    ),",
                "    __FinalOutput = Table.SelectColumns(__WithMissingColumns, __BimColumns, MissingField.UseNull)",
                "in",
                "    __FinalOutput"
              ]
            }
          }
        ]
      },
      {
        "name": "sales_1M_workflow",
        "columns": [
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ProductCategory",
            "dataType": "string",
            "sourceColumn": "ProductCategory",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "TotalSales",
            "dataType": "string",
            "sourceColumn": "TotalSales",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "TotalQuantity",
            "dataType": "string",
            "sourceColumn": "TotalQuantity",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AvgSalesPerUnit",
            "dataType": "string",
            "sourceColumn": "AvgSalesPerUnit",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "sales_1M_workflow-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    __Source = (let",
                "    Source = SharePoint.Files(\"https://sorimtechnologies.sharepoint.com\", [ApiVersion = 15]),",
                "    MatchingFiles = Table.SelectRows(Source, each [Name] = \"sales_data_1M.csv\"),",
                "    FileContent = if Table.RowCount(MatchingFiles) = 0 then error \"File not found in SharePoint: sales_data_1M.csv\" else MatchingFiles{0}[Content],",
                "    CsvData = Csv.Document(FileContent, [Delimiter = \",\", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(CsvData, [PromoteAllScalars = true]),",
                "    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, List.Transform(Table.ColumnNames(PromotedHeaders), each {_, type text})),",
                "    Checkpoint_1 = ChangedTypes,",
                "    SelectedFields_2 = let cols = Table.ColumnNames(Checkpoint_1), ops = {{\"CustomerID\", Int64.Type}, {\"CustomerName\", type text}, {\"Region\", type text}, {\"City\", type text}, {\"ProductCategory\", type text}, {\"ProductName\", type text}, {\"Quantity\", Int64.Type}, {\"UnitPrice\", type number}, {\"SalesAmount\", type number}, {\"Discount\", type number}, {\"OrderDate\", type date}, {\"Status\", type text}, {\"PaymentMethod\", type text}}, TypedColumns = Table.TransformColumnTypes(Checkpoint_1, List.Select(ops, each List.Contains(cols, _{0}))) in Table.SelectColumns(TypedColumns, {\"CustomerID\", \"CustomerName\", \"Region\", \"City\", \"ProductCategory\", \"ProductName\", \"Quantity\", \"UnitPrice\", \"SalesAmount\", \"Discount\", \"OrderDate\", \"Status\", \"PaymentMethod\"}, MissingField.UseNull),",
                "    FilteredRows_3 = let required = {\"SalesAmount\", \"Region\"}, existing = Table.ColumnNames(SelectedFields_2), missing = List.Difference(required, existing) in if List.Count(missing) > 0 then SelectedFields_2 else Table.SelectRows(SelectedFields_2, each try ([SalesAmount] > 1000 and [Region] = \"North\") otherwise false),",
                "    GroupedData_4 = let Input = let required = {\"Region\", \"ProductCategory\", \"SalesAmount\", \"Quantity\"}, existing = Table.ColumnNames(FilteredRows_3), missing = List.Difference(required, existing) in List.Accumulate(missing, FilteredRows_3, (state, col) => Table.AddColumn(state, col, each null, type any)) in Table.Group(Input, {\"Region\", \"ProductCategory\"}, {{\"TotalSales\", each List.Sum([SalesAmount]), type number}, {\"TotalQuantity\", each List.Sum([Quantity]), type number}}),",
                "    Calculated_AvgSalesPerUnit_5 = let Input = let required = {\"TotalQuantity\", \"TotalSales\"}, existing = Table.ColumnNames(GroupedData_4), missing = List.Difference(required, existing) in List.Accumulate(missing, GroupedData_4, (state, col) => Table.AddColumn(state, col, each null, type any)) in Table.AddColumn(Input, \"AvgSalesPerUnit\", each try (if [TotalQuantity] = 0 then null else [TotalSales] / [TotalQuantity]) otherwise null, type number),",
                "    Checkpoint_6 = Calculated_AvgSalesPerUnit_5",
                "in",
                "    Checkpoint_6),",
                "    __BimColumns = {\"Region\", \"ProductCategory\", \"TotalSales\", \"TotalQuantity\", \"AvgSalesPerUnit\"},",
                "    __SafeBase = try",
                "        __Source",
                "    otherwise",
                "        Table.FromRecords({{}}, __BimColumns),",
                "    __AvailableColumns = List.Intersect({{Table.ColumnNames(__SafeBase), __BimColumns}}, MissingField.Error),",
                "    __WithMissingColumns = List.Accumulate(",
                "        List.Difference(__BimColumns, __AvailableColumns),",
                "        __SafeBase,",
                "        (tbl, col) => Table.AddColumn(tbl, col, each null, type any)",
                "    ),",
                "    __FinalOutput = Table.SelectColumns(__WithMissingColumns, __BimColumns, MissingField.UseNull)",
                "in",
                "    __FinalOutput"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "sales_1M_workflow_Region_sales_data_1M_raw_Region",
        "fromTable": "sales_1M_workflow",
        "fromColumn": "Region",
        "toTable": "sales_data_1M_raw",
        "toColumn": "Region",
        "crossFilteringBehavior": "oneDirection",
        "fromCardinality": "many",
        "toCardinality": "one"
      }
    ],
    "expressions": [
      {
        "name": "DataSourcePath",
        "kind": "m",
        "expression": [
          "\"C:\\Data\\sales_data_1M.csv\""
        ],
        "annotations": [
          {
            "name": "IsParameterQuery",
            "value": "True"
          },
          {
            "name": "IsParameterQueryRequired",
            "value": "False"
          },
          {
            "name": "PBI_QueryOrder",
            "value": "0"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.130.930.0"
      },
      {
        "name": "createdBy",
        "value": "QlikAI_Accelerator"
      }
    ]
  }
}