{
  "name": "Workflow_Iterative_Macro_Salary_Equaliser_500K_rows",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "iterative_sample_data_raw",
        "columns": [],
        "partitions": [
          {
            "name": "iterative_sample_data_raw-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = SharePoint.Files(\"https://sorimtechnologies.sharepoint.com\", [ApiVersion = 15]),",
                "    MatchingFiles = Table.SelectRows(Source, each [Name] = \"iterative_sample_data.csv\"),",
                "    FileContent = if Table.RowCount(MatchingFiles) = 0 then error \"File not found in SharePoint: iterative_sample_data.csv\" else MatchingFiles{0}[Content],",
                "    CsvData = Csv.Document(FileContent, [Delimiter = \",\", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(CsvData, [PromoteAllScalars = true]),",
                "    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, List.Transform(Table.ColumnNames(PromotedHeaders), each {_, type text}))",
                "in",
                "    ChangedTypes"
              ]
            }
          }
        ]
      },
      {
        "name": "Workflow_Iterative_Macro_Salary_Equaliser_500K_rows",
        "columns": [
          {
            "name": "BaseSalary",
            "dataType": "string",
            "sourceColumn": "BaseSalary",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Workflow_Iterative_Macro_Salary_Equaliser_500K_rows-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    __Source = (let",
                "    Source = SharePoint.Files(\"https://sorimtechnologies.sharepoint.com\", [ApiVersion = 15]),",
                "    MatchingFiles = Table.SelectRows(Source, each [Name] = \"iterative_sample_data.csv\"),",
                "    FileContent = if Table.RowCount(MatchingFiles) = 0 then error \"File not found in SharePoint: iterative_sample_data.csv\" else MatchingFiles{0}[Content],",
                "    CsvData = Csv.Document(FileContent, [Delimiter = \",\", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(CsvData, [PromoteAllScalars = true]),",
                "    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, List.Transform(Table.ColumnNames(PromotedHeaders), each {_, type text})),",
                "    Checkpoint_1 = ChangedTypes,",
                "    FilteredRows_2 = let required = {\"BaseSalary\"}, existing = Table.ColumnNames(Checkpoint_1), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then Checkpoint_1 else Table.SelectRows(Checkpoint_1, each try ([BaseSalary] < 120000) otherwise false),",
                "    ManualReview_3 = FilteredRows_2,",
                "    Checkpoint_4 = ManualReview_3,",
                "    SortedRows_5 = Checkpoint_4,",
                "    Checkpoint_6 = SortedRows_5",
                "in",
                "    Checkpoint_6),",
                "    __BimColumns = {\"BaseSalary\"},",
                "    __SafeBase = try",
                "        __Source",
                "    otherwise",
                "        Table.FromRecords({{}}, __BimColumns),",
                "    __ExistingColumns = Table.ColumnNames(__SafeBase),",
                "    __MissingColumns = List.Select(__BimColumns, each not List.Contains(__ExistingColumns, _, Comparer.OrdinalIgnoreCase)),",
                "    __WithMissingColumns = List.Accumulate(",
                "        __MissingColumns,",
                "        __SafeBase,",
                "        (tbl, col) => if Table.HasColumns(tbl, col) then tbl else Table.AddColumn(tbl, col, each null, type any)",
                "    ),",
                "    __FinalOutput = Table.SelectColumns(__WithMissingColumns, __BimColumns, MissingField.UseNull)",
                "in",
                "    __FinalOutput"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [],
    "expressions": [
      {
        "name": "DataSourcePath",
        "kind": "m",
        "expression": [
          "\"iterative_sample_data.csv\""
        ],
        "annotations": [
          {
            "name": "IsParameterQuery",
            "value": "True"
          },
          {
            "name": "IsParameterQueryRequired",
            "value": "False"
          },
          {
            "name": "PBI_QueryOrder",
            "value": "0"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.130.930.0"
      },
      {
        "name": "createdBy",
        "value": "QlikAI_Accelerator"
      }
    ]
  }
}