{
  "name": "Mega_Transformation_Workflow_600_Tools",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "large_fact_100k_raw",
        "columns": [],
        "partitions": [
          {
            "name": "large_fact_100k_raw-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = SharePoint.Files(\"https://sorimtechnologies.sharepoint.com\", [ApiVersion = 15]),",
                "    MatchingFiles = Table.SelectRows(Source, each [Name] = \"large_fact_100k.csv\"),",
                "    FileContent = if Table.RowCount(MatchingFiles) = 0 then error \"File not found in SharePoint: large_fact_100k.csv\" else MatchingFiles{0}[Content],",
                "    CsvData = Csv.Document(FileContent, [Delimiter = \",\", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(CsvData, [PromoteAllScalars = true]),",
                "    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, List.Transform(Table.ColumnNames(PromotedHeaders), each {_, type text}))",
                "in",
                "    ChangedTypes"
              ]
            }
          }
        ]
      },
      {
        "name": "Mega_Transformation_Workflow_600_Tools",
        "columns": [
          {
            "name": "MetricA",
            "dataType": "string",
            "sourceColumn": "MetricA",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Mega_Transformation_Workflow_600_Tools-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    __Source = (let",
                "    Source = SharePoint.Files(\"https://sorimtechnologies.sharepoint.com\", [ApiVersion = 15]),",
                "    MatchingFiles = Table.SelectRows(Source, each [Name] = \"large_fact_100k.csv\"),",
                "    FileContent = if Table.RowCount(MatchingFiles) = 0 then error \"File not found in SharePoint: large_fact_100k.csv\" else MatchingFiles{0}[Content],",
                "    CsvData = Csv.Document(FileContent, [Delimiter = \",\", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(CsvData, [PromoteAllScalars = true]),",
                "    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, List.Transform(Table.ColumnNames(PromotedHeaders), each {_, type text})),",
                "    Checkpoint_1 = ChangedTypes,",
                "    SelectedColumns_2 = Checkpoint_1,",
                "    FormulaApplied_3 = SelectedColumns_2,",
                "    FilteredRows_4 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_3), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_3 else Table.SelectRows(FormulaApplied_3, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_5 = let Input = FilteredRows_4 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_6 = GroupedData_5,",
                "    UnionPrepared_7 = JoinPrepared_6,",
                "    SelectedColumns_8 = UnionPrepared_7,",
                "    FormulaApplied_9 = SelectedColumns_8,",
                "    FilteredRows_10 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_9), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_9 else Table.SelectRows(FormulaApplied_9, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_11 = let Input = FilteredRows_10 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_12 = GroupedData_11,",
                "    UnionPrepared_13 = JoinPrepared_12,",
                "    SelectedColumns_14 = UnionPrepared_13,",
                "    FormulaApplied_15 = SelectedColumns_14,",
                "    FilteredRows_16 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_15), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_15 else Table.SelectRows(FormulaApplied_15, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_17 = let Input = FilteredRows_16 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_18 = GroupedData_17,",
                "    UnionPrepared_19 = JoinPrepared_18,",
                "    SelectedColumns_20 = UnionPrepared_19,",
                "    FormulaApplied_21 = SelectedColumns_20,",
                "    FilteredRows_22 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_21), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_21 else Table.SelectRows(FormulaApplied_21, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_23 = let Input = FilteredRows_22 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_24 = GroupedData_23,",
                "    UnionPrepared_25 = JoinPrepared_24,",
                "    SelectedColumns_26 = UnionPrepared_25,",
                "    FormulaApplied_27 = SelectedColumns_26,",
                "    FilteredRows_28 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_27), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_27 else Table.SelectRows(FormulaApplied_27, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_29 = let Input = FilteredRows_28 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_30 = GroupedData_29,",
                "    UnionPrepared_31 = JoinPrepared_30,",
                "    SelectedColumns_32 = UnionPrepared_31,",
                "    FormulaApplied_33 = SelectedColumns_32,",
                "    FilteredRows_34 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_33), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_33 else Table.SelectRows(FormulaApplied_33, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_35 = let Input = FilteredRows_34 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_36 = GroupedData_35,",
                "    UnionPrepared_37 = JoinPrepared_36,",
                "    SelectedColumns_38 = UnionPrepared_37,",
                "    FormulaApplied_39 = SelectedColumns_38,",
                "    FilteredRows_40 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_39), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_39 else Table.SelectRows(FormulaApplied_39, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_41 = let Input = FilteredRows_40 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_42 = GroupedData_41,",
                "    UnionPrepared_43 = JoinPrepared_42,",
                "    SelectedColumns_44 = UnionPrepared_43,",
                "    FormulaApplied_45 = SelectedColumns_44,",
                "    FilteredRows_46 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_45), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_45 else Table.SelectRows(FormulaApplied_45, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_47 = let Input = FilteredRows_46 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_48 = GroupedData_47,",
                "    UnionPrepared_49 = JoinPrepared_48,",
                "    SelectedColumns_50 = UnionPrepared_49,",
                "    FormulaApplied_51 = SelectedColumns_50,",
                "    FilteredRows_52 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_51), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_51 else Table.SelectRows(FormulaApplied_51, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_53 = let Input = FilteredRows_52 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_54 = GroupedData_53,",
                "    UnionPrepared_55 = JoinPrepared_54,",
                "    SelectedColumns_56 = UnionPrepared_55,",
                "    FormulaApplied_57 = SelectedColumns_56,",
                "    FilteredRows_58 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_57), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_57 else Table.SelectRows(FormulaApplied_57, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_59 = let Input = FilteredRows_58 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_60 = GroupedData_59,",
                "    UnionPrepared_61 = JoinPrepared_60,",
                "    SelectedColumns_62 = UnionPrepared_61,",
                "    FormulaApplied_63 = SelectedColumns_62,",
                "    FilteredRows_64 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_63), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_63 else Table.SelectRows(FormulaApplied_63, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_65 = let Input = FilteredRows_64 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_66 = GroupedData_65,",
                "    UnionPrepared_67 = JoinPrepared_66,",
                "    SelectedColumns_68 = UnionPrepared_67,",
                "    FormulaApplied_69 = SelectedColumns_68,",
                "    FilteredRows_70 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_69), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_69 else Table.SelectRows(FormulaApplied_69, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_71 = let Input = FilteredRows_70 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_72 = GroupedData_71,",
                "    UnionPrepared_73 = JoinPrepared_72,",
                "    SelectedColumns_74 = UnionPrepared_73,",
                "    FormulaApplied_75 = SelectedColumns_74,",
                "    FilteredRows_76 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_75), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_75 else Table.SelectRows(FormulaApplied_75, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_77 = let Input = FilteredRows_76 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_78 = GroupedData_77,",
                "    UnionPrepared_79 = JoinPrepared_78,",
                "    SelectedColumns_80 = UnionPrepared_79,",
                "    FormulaApplied_81 = SelectedColumns_80,",
                "    FilteredRows_82 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_81), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_81 else Table.SelectRows(FormulaApplied_81, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_83 = let Input = FilteredRows_82 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_84 = GroupedData_83,",
                "    UnionPrepared_85 = JoinPrepared_84,",
                "    SelectedColumns_86 = UnionPrepared_85,",
                "    FormulaApplied_87 = SelectedColumns_86,",
                "    FilteredRows_88 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_87), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_87 else Table.SelectRows(FormulaApplied_87, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_89 = let Input = FilteredRows_88 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_90 = GroupedData_89,",
                "    UnionPrepared_91 = JoinPrepared_90,",
                "    SelectedColumns_92 = UnionPrepared_91,",
                "    FormulaApplied_93 = SelectedColumns_92,",
                "    FilteredRows_94 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_93), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_93 else Table.SelectRows(FormulaApplied_93, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_95 = let Input = FilteredRows_94 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_96 = GroupedData_95,",
                "    UnionPrepared_97 = JoinPrepared_96,",
                "    SelectedColumns_98 = UnionPrepared_97,",
                "    FormulaApplied_99 = SelectedColumns_98,",
                "    FilteredRows_100 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_99), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_99 else Table.SelectRows(FormulaApplied_99, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_101 = let Input = FilteredRows_100 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_102 = GroupedData_101,",
                "    UnionPrepared_103 = JoinPrepared_102,",
                "    SelectedColumns_104 = UnionPrepared_103,",
                "    FormulaApplied_105 = SelectedColumns_104,",
                "    FilteredRows_106 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_105), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_105 else Table.SelectRows(FormulaApplied_105, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_107 = let Input = FilteredRows_106 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_108 = GroupedData_107,",
                "    UnionPrepared_109 = JoinPrepared_108,",
                "    SelectedColumns_110 = UnionPrepared_109,",
                "    FormulaApplied_111 = SelectedColumns_110,",
                "    FilteredRows_112 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_111), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_111 else Table.SelectRows(FormulaApplied_111, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_113 = let Input = FilteredRows_112 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_114 = GroupedData_113,",
                "    UnionPrepared_115 = JoinPrepared_114,",
                "    SelectedColumns_116 = UnionPrepared_115,",
                "    FormulaApplied_117 = SelectedColumns_116,",
                "    FilteredRows_118 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_117), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_117 else Table.SelectRows(FormulaApplied_117, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_119 = let Input = FilteredRows_118 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_120 = GroupedData_119,",
                "    UnionPrepared_121 = JoinPrepared_120,",
                "    SelectedColumns_122 = UnionPrepared_121,",
                "    FormulaApplied_123 = SelectedColumns_122,",
                "    FilteredRows_124 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_123), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_123 else Table.SelectRows(FormulaApplied_123, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_125 = let Input = FilteredRows_124 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_126 = GroupedData_125,",
                "    UnionPrepared_127 = JoinPrepared_126,",
                "    SelectedColumns_128 = UnionPrepared_127,",
                "    FormulaApplied_129 = SelectedColumns_128,",
                "    FilteredRows_130 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_129), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_129 else Table.SelectRows(FormulaApplied_129, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_131 = let Input = FilteredRows_130 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_132 = GroupedData_131,",
                "    UnionPrepared_133 = JoinPrepared_132,",
                "    SelectedColumns_134 = UnionPrepared_133,",
                "    FormulaApplied_135 = SelectedColumns_134,",
                "    FilteredRows_136 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_135), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_135 else Table.SelectRows(FormulaApplied_135, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_137 = let Input = FilteredRows_136 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_138 = GroupedData_137,",
                "    UnionPrepared_139 = JoinPrepared_138,",
                "    SelectedColumns_140 = UnionPrepared_139,",
                "    FormulaApplied_141 = SelectedColumns_140,",
                "    FilteredRows_142 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_141), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_141 else Table.SelectRows(FormulaApplied_141, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_143 = let Input = FilteredRows_142 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_144 = GroupedData_143,",
                "    UnionPrepared_145 = JoinPrepared_144,",
                "    SelectedColumns_146 = UnionPrepared_145,",
                "    FormulaApplied_147 = SelectedColumns_146,",
                "    FilteredRows_148 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_147), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_147 else Table.SelectRows(FormulaApplied_147, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_149 = let Input = FilteredRows_148 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_150 = GroupedData_149,",
                "    UnionPrepared_151 = JoinPrepared_150,",
                "    SelectedColumns_152 = UnionPrepared_151,",
                "    FormulaApplied_153 = SelectedColumns_152,",
                "    FilteredRows_154 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_153), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_153 else Table.SelectRows(FormulaApplied_153, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_155 = let Input = FilteredRows_154 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_156 = GroupedData_155,",
                "    UnionPrepared_157 = JoinPrepared_156,",
                "    SelectedColumns_158 = UnionPrepared_157,",
                "    FormulaApplied_159 = SelectedColumns_158,",
                "    FilteredRows_160 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_159), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_159 else Table.SelectRows(FormulaApplied_159, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_161 = let Input = FilteredRows_160 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_162 = GroupedData_161,",
                "    UnionPrepared_163 = JoinPrepared_162,",
                "    SelectedColumns_164 = UnionPrepared_163,",
                "    FormulaApplied_165 = SelectedColumns_164,",
                "    FilteredRows_166 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_165), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_165 else Table.SelectRows(FormulaApplied_165, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_167 = let Input = FilteredRows_166 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_168 = GroupedData_167,",
                "    UnionPrepared_169 = JoinPrepared_168,",
                "    SelectedColumns_170 = UnionPrepared_169,",
                "    FormulaApplied_171 = SelectedColumns_170,",
                "    FilteredRows_172 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_171), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_171 else Table.SelectRows(FormulaApplied_171, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_173 = let Input = FilteredRows_172 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_174 = GroupedData_173,",
                "    UnionPrepared_175 = JoinPrepared_174,",
                "    SelectedColumns_176 = UnionPrepared_175,",
                "    FormulaApplied_177 = SelectedColumns_176,",
                "    FilteredRows_178 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_177), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_177 else Table.SelectRows(FormulaApplied_177, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_179 = let Input = FilteredRows_178 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_180 = GroupedData_179,",
                "    UnionPrepared_181 = JoinPrepared_180,",
                "    SelectedColumns_182 = UnionPrepared_181,",
                "    FormulaApplied_183 = SelectedColumns_182,",
                "    FilteredRows_184 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_183), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_183 else Table.SelectRows(FormulaApplied_183, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_185 = let Input = FilteredRows_184 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_186 = GroupedData_185,",
                "    UnionPrepared_187 = JoinPrepared_186,",
                "    SelectedColumns_188 = UnionPrepared_187,",
                "    FormulaApplied_189 = SelectedColumns_188,",
                "    FilteredRows_190 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_189), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_189 else Table.SelectRows(FormulaApplied_189, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_191 = let Input = FilteredRows_190 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_192 = GroupedData_191,",
                "    UnionPrepared_193 = JoinPrepared_192,",
                "    SelectedColumns_194 = UnionPrepared_193,",
                "    FormulaApplied_195 = SelectedColumns_194,",
                "    FilteredRows_196 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_195), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_195 else Table.SelectRows(FormulaApplied_195, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_197 = let Input = FilteredRows_196 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_198 = GroupedData_197,",
                "    UnionPrepared_199 = JoinPrepared_198,",
                "    SelectedColumns_200 = UnionPrepared_199,",
                "    FormulaApplied_201 = SelectedColumns_200,",
                "    FilteredRows_202 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_201), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_201 else Table.SelectRows(FormulaApplied_201, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_203 = let Input = FilteredRows_202 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_204 = GroupedData_203,",
                "    UnionPrepared_205 = JoinPrepared_204,",
                "    SelectedColumns_206 = UnionPrepared_205,",
                "    FormulaApplied_207 = SelectedColumns_206,",
                "    FilteredRows_208 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_207), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_207 else Table.SelectRows(FormulaApplied_207, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_209 = let Input = FilteredRows_208 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_210 = GroupedData_209,",
                "    UnionPrepared_211 = JoinPrepared_210,",
                "    SelectedColumns_212 = UnionPrepared_211,",
                "    FormulaApplied_213 = SelectedColumns_212,",
                "    FilteredRows_214 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_213), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_213 else Table.SelectRows(FormulaApplied_213, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_215 = let Input = FilteredRows_214 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_216 = GroupedData_215,",
                "    UnionPrepared_217 = JoinPrepared_216,",
                "    SelectedColumns_218 = UnionPrepared_217,",
                "    FormulaApplied_219 = SelectedColumns_218,",
                "    FilteredRows_220 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_219), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_219 else Table.SelectRows(FormulaApplied_219, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_221 = let Input = FilteredRows_220 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_222 = GroupedData_221,",
                "    UnionPrepared_223 = JoinPrepared_222,",
                "    SelectedColumns_224 = UnionPrepared_223,",
                "    FormulaApplied_225 = SelectedColumns_224,",
                "    FilteredRows_226 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_225), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_225 else Table.SelectRows(FormulaApplied_225, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_227 = let Input = FilteredRows_226 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_228 = GroupedData_227,",
                "    UnionPrepared_229 = JoinPrepared_228,",
                "    SelectedColumns_230 = UnionPrepared_229,",
                "    FormulaApplied_231 = SelectedColumns_230,",
                "    FilteredRows_232 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_231), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_231 else Table.SelectRows(FormulaApplied_231, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_233 = let Input = FilteredRows_232 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_234 = GroupedData_233,",
                "    UnionPrepared_235 = JoinPrepared_234,",
                "    SelectedColumns_236 = UnionPrepared_235,",
                "    FormulaApplied_237 = SelectedColumns_236,",
                "    FilteredRows_238 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_237), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_237 else Table.SelectRows(FormulaApplied_237, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_239 = let Input = FilteredRows_238 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_240 = GroupedData_239,",
                "    UnionPrepared_241 = JoinPrepared_240,",
                "    SelectedColumns_242 = UnionPrepared_241,",
                "    FormulaApplied_243 = SelectedColumns_242,",
                "    FilteredRows_244 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_243), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_243 else Table.SelectRows(FormulaApplied_243, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_245 = let Input = FilteredRows_244 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_246 = GroupedData_245,",
                "    UnionPrepared_247 = JoinPrepared_246,",
                "    SelectedColumns_248 = UnionPrepared_247,",
                "    FormulaApplied_249 = SelectedColumns_248,",
                "    FilteredRows_250 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_249), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_249 else Table.SelectRows(FormulaApplied_249, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_251 = let Input = FilteredRows_250 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_252 = GroupedData_251,",
                "    UnionPrepared_253 = JoinPrepared_252,",
                "    SelectedColumns_254 = UnionPrepared_253,",
                "    FormulaApplied_255 = SelectedColumns_254,",
                "    FilteredRows_256 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_255), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_255 else Table.SelectRows(FormulaApplied_255, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_257 = let Input = FilteredRows_256 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_258 = GroupedData_257,",
                "    UnionPrepared_259 = JoinPrepared_258,",
                "    SelectedColumns_260 = UnionPrepared_259,",
                "    FormulaApplied_261 = SelectedColumns_260,",
                "    FilteredRows_262 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_261), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_261 else Table.SelectRows(FormulaApplied_261, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_263 = let Input = FilteredRows_262 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_264 = GroupedData_263,",
                "    UnionPrepared_265 = JoinPrepared_264,",
                "    SelectedColumns_266 = UnionPrepared_265,",
                "    FormulaApplied_267 = SelectedColumns_266,",
                "    FilteredRows_268 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_267), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_267 else Table.SelectRows(FormulaApplied_267, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_269 = let Input = FilteredRows_268 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_270 = GroupedData_269,",
                "    UnionPrepared_271 = JoinPrepared_270,",
                "    SelectedColumns_272 = UnionPrepared_271,",
                "    FormulaApplied_273 = SelectedColumns_272,",
                "    FilteredRows_274 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_273), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_273 else Table.SelectRows(FormulaApplied_273, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_275 = let Input = FilteredRows_274 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_276 = GroupedData_275,",
                "    UnionPrepared_277 = JoinPrepared_276,",
                "    SelectedColumns_278 = UnionPrepared_277,",
                "    FormulaApplied_279 = SelectedColumns_278,",
                "    FilteredRows_280 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_279), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_279 else Table.SelectRows(FormulaApplied_279, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_281 = let Input = FilteredRows_280 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_282 = GroupedData_281,",
                "    UnionPrepared_283 = JoinPrepared_282,",
                "    SelectedColumns_284 = UnionPrepared_283,",
                "    FormulaApplied_285 = SelectedColumns_284,",
                "    FilteredRows_286 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_285), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_285 else Table.SelectRows(FormulaApplied_285, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_287 = let Input = FilteredRows_286 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_288 = GroupedData_287,",
                "    UnionPrepared_289 = JoinPrepared_288,",
                "    SelectedColumns_290 = UnionPrepared_289,",
                "    FormulaApplied_291 = SelectedColumns_290,",
                "    FilteredRows_292 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_291), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_291 else Table.SelectRows(FormulaApplied_291, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_293 = let Input = FilteredRows_292 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_294 = GroupedData_293,",
                "    UnionPrepared_295 = JoinPrepared_294,",
                "    SelectedColumns_296 = UnionPrepared_295,",
                "    FormulaApplied_297 = SelectedColumns_296,",
                "    FilteredRows_298 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_297), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_297 else Table.SelectRows(FormulaApplied_297, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_299 = let Input = FilteredRows_298 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_300 = GroupedData_299,",
                "    UnionPrepared_301 = JoinPrepared_300,",
                "    SelectedColumns_302 = UnionPrepared_301,",
                "    FormulaApplied_303 = SelectedColumns_302,",
                "    FilteredRows_304 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_303), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_303 else Table.SelectRows(FormulaApplied_303, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_305 = let Input = FilteredRows_304 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_306 = GroupedData_305,",
                "    UnionPrepared_307 = JoinPrepared_306,",
                "    SelectedColumns_308 = UnionPrepared_307,",
                "    FormulaApplied_309 = SelectedColumns_308,",
                "    FilteredRows_310 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_309), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_309 else Table.SelectRows(FormulaApplied_309, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_311 = let Input = FilteredRows_310 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_312 = GroupedData_311,",
                "    UnionPrepared_313 = JoinPrepared_312,",
                "    SelectedColumns_314 = UnionPrepared_313,",
                "    FormulaApplied_315 = SelectedColumns_314,",
                "    FilteredRows_316 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_315), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_315 else Table.SelectRows(FormulaApplied_315, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_317 = let Input = FilteredRows_316 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_318 = GroupedData_317,",
                "    UnionPrepared_319 = JoinPrepared_318,",
                "    SelectedColumns_320 = UnionPrepared_319,",
                "    FormulaApplied_321 = SelectedColumns_320,",
                "    FilteredRows_322 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_321), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_321 else Table.SelectRows(FormulaApplied_321, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_323 = let Input = FilteredRows_322 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_324 = GroupedData_323,",
                "    UnionPrepared_325 = JoinPrepared_324,",
                "    SelectedColumns_326 = UnionPrepared_325,",
                "    FormulaApplied_327 = SelectedColumns_326,",
                "    FilteredRows_328 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_327), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_327 else Table.SelectRows(FormulaApplied_327, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_329 = let Input = FilteredRows_328 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_330 = GroupedData_329,",
                "    UnionPrepared_331 = JoinPrepared_330,",
                "    SelectedColumns_332 = UnionPrepared_331,",
                "    FormulaApplied_333 = SelectedColumns_332,",
                "    FilteredRows_334 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_333), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_333 else Table.SelectRows(FormulaApplied_333, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_335 = let Input = FilteredRows_334 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_336 = GroupedData_335,",
                "    UnionPrepared_337 = JoinPrepared_336,",
                "    SelectedColumns_338 = UnionPrepared_337,",
                "    FormulaApplied_339 = SelectedColumns_338,",
                "    FilteredRows_340 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_339), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_339 else Table.SelectRows(FormulaApplied_339, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_341 = let Input = FilteredRows_340 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_342 = GroupedData_341,",
                "    UnionPrepared_343 = JoinPrepared_342,",
                "    SelectedColumns_344 = UnionPrepared_343,",
                "    FormulaApplied_345 = SelectedColumns_344,",
                "    FilteredRows_346 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_345), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_345 else Table.SelectRows(FormulaApplied_345, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_347 = let Input = FilteredRows_346 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_348 = GroupedData_347,",
                "    UnionPrepared_349 = JoinPrepared_348,",
                "    SelectedColumns_350 = UnionPrepared_349,",
                "    FormulaApplied_351 = SelectedColumns_350,",
                "    FilteredRows_352 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_351), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_351 else Table.SelectRows(FormulaApplied_351, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_353 = let Input = FilteredRows_352 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_354 = GroupedData_353,",
                "    UnionPrepared_355 = JoinPrepared_354,",
                "    SelectedColumns_356 = UnionPrepared_355,",
                "    FormulaApplied_357 = SelectedColumns_356,",
                "    FilteredRows_358 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_357), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_357 else Table.SelectRows(FormulaApplied_357, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_359 = let Input = FilteredRows_358 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_360 = GroupedData_359,",
                "    UnionPrepared_361 = JoinPrepared_360,",
                "    SelectedColumns_362 = UnionPrepared_361,",
                "    FormulaApplied_363 = SelectedColumns_362,",
                "    FilteredRows_364 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_363), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_363 else Table.SelectRows(FormulaApplied_363, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_365 = let Input = FilteredRows_364 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_366 = GroupedData_365,",
                "    UnionPrepared_367 = JoinPrepared_366,",
                "    SelectedColumns_368 = UnionPrepared_367,",
                "    FormulaApplied_369 = SelectedColumns_368,",
                "    FilteredRows_370 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_369), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_369 else Table.SelectRows(FormulaApplied_369, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_371 = let Input = FilteredRows_370 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_372 = GroupedData_371,",
                "    UnionPrepared_373 = JoinPrepared_372,",
                "    SelectedColumns_374 = UnionPrepared_373,",
                "    FormulaApplied_375 = SelectedColumns_374,",
                "    FilteredRows_376 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_375), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_375 else Table.SelectRows(FormulaApplied_375, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_377 = let Input = FilteredRows_376 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_378 = GroupedData_377,",
                "    UnionPrepared_379 = JoinPrepared_378,",
                "    SelectedColumns_380 = UnionPrepared_379,",
                "    FormulaApplied_381 = SelectedColumns_380,",
                "    FilteredRows_382 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_381), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_381 else Table.SelectRows(FormulaApplied_381, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_383 = let Input = FilteredRows_382 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_384 = GroupedData_383,",
                "    UnionPrepared_385 = JoinPrepared_384,",
                "    SelectedColumns_386 = UnionPrepared_385,",
                "    FormulaApplied_387 = SelectedColumns_386,",
                "    FilteredRows_388 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_387), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_387 else Table.SelectRows(FormulaApplied_387, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_389 = let Input = FilteredRows_388 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_390 = GroupedData_389,",
                "    UnionPrepared_391 = JoinPrepared_390,",
                "    SelectedColumns_392 = UnionPrepared_391,",
                "    FormulaApplied_393 = SelectedColumns_392,",
                "    FilteredRows_394 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_393), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_393 else Table.SelectRows(FormulaApplied_393, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_395 = let Input = FilteredRows_394 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_396 = GroupedData_395,",
                "    UnionPrepared_397 = JoinPrepared_396,",
                "    SelectedColumns_398 = UnionPrepared_397,",
                "    FormulaApplied_399 = SelectedColumns_398,",
                "    FilteredRows_400 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_399), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_399 else Table.SelectRows(FormulaApplied_399, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_401 = let Input = FilteredRows_400 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_402 = GroupedData_401,",
                "    UnionPrepared_403 = JoinPrepared_402,",
                "    SelectedColumns_404 = UnionPrepared_403,",
                "    FormulaApplied_405 = SelectedColumns_404,",
                "    FilteredRows_406 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_405), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_405 else Table.SelectRows(FormulaApplied_405, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_407 = let Input = FilteredRows_406 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_408 = GroupedData_407,",
                "    UnionPrepared_409 = JoinPrepared_408,",
                "    SelectedColumns_410 = UnionPrepared_409,",
                "    FormulaApplied_411 = SelectedColumns_410,",
                "    FilteredRows_412 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_411), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_411 else Table.SelectRows(FormulaApplied_411, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_413 = let Input = FilteredRows_412 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_414 = GroupedData_413,",
                "    UnionPrepared_415 = JoinPrepared_414,",
                "    SelectedColumns_416 = UnionPrepared_415,",
                "    FormulaApplied_417 = SelectedColumns_416,",
                "    FilteredRows_418 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_417), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_417 else Table.SelectRows(FormulaApplied_417, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_419 = let Input = FilteredRows_418 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_420 = GroupedData_419,",
                "    UnionPrepared_421 = JoinPrepared_420,",
                "    SelectedColumns_422 = UnionPrepared_421,",
                "    FormulaApplied_423 = SelectedColumns_422,",
                "    FilteredRows_424 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_423), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_423 else Table.SelectRows(FormulaApplied_423, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_425 = let Input = FilteredRows_424 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_426 = GroupedData_425,",
                "    UnionPrepared_427 = JoinPrepared_426,",
                "    SelectedColumns_428 = UnionPrepared_427,",
                "    FormulaApplied_429 = SelectedColumns_428,",
                "    FilteredRows_430 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_429), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_429 else Table.SelectRows(FormulaApplied_429, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_431 = let Input = FilteredRows_430 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_432 = GroupedData_431,",
                "    UnionPrepared_433 = JoinPrepared_432,",
                "    SelectedColumns_434 = UnionPrepared_433,",
                "    FormulaApplied_435 = SelectedColumns_434,",
                "    FilteredRows_436 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_435), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_435 else Table.SelectRows(FormulaApplied_435, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_437 = let Input = FilteredRows_436 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_438 = GroupedData_437,",
                "    UnionPrepared_439 = JoinPrepared_438,",
                "    SelectedColumns_440 = UnionPrepared_439,",
                "    FormulaApplied_441 = SelectedColumns_440,",
                "    FilteredRows_442 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_441), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_441 else Table.SelectRows(FormulaApplied_441, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_443 = let Input = FilteredRows_442 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_444 = GroupedData_443,",
                "    UnionPrepared_445 = JoinPrepared_444,",
                "    SelectedColumns_446 = UnionPrepared_445,",
                "    FormulaApplied_447 = SelectedColumns_446,",
                "    FilteredRows_448 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_447), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_447 else Table.SelectRows(FormulaApplied_447, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_449 = let Input = FilteredRows_448 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_450 = GroupedData_449,",
                "    UnionPrepared_451 = JoinPrepared_450,",
                "    SelectedColumns_452 = UnionPrepared_451,",
                "    FormulaApplied_453 = SelectedColumns_452,",
                "    FilteredRows_454 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_453), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_453 else Table.SelectRows(FormulaApplied_453, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_455 = let Input = FilteredRows_454 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_456 = GroupedData_455,",
                "    UnionPrepared_457 = JoinPrepared_456,",
                "    SelectedColumns_458 = UnionPrepared_457,",
                "    FormulaApplied_459 = SelectedColumns_458,",
                "    FilteredRows_460 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_459), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_459 else Table.SelectRows(FormulaApplied_459, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_461 = let Input = FilteredRows_460 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_462 = GroupedData_461,",
                "    UnionPrepared_463 = JoinPrepared_462,",
                "    SelectedColumns_464 = UnionPrepared_463,",
                "    FormulaApplied_465 = SelectedColumns_464,",
                "    FilteredRows_466 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_465), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_465 else Table.SelectRows(FormulaApplied_465, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_467 = let Input = FilteredRows_466 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_468 = GroupedData_467,",
                "    UnionPrepared_469 = JoinPrepared_468,",
                "    SelectedColumns_470 = UnionPrepared_469,",
                "    FormulaApplied_471 = SelectedColumns_470,",
                "    FilteredRows_472 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_471), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_471 else Table.SelectRows(FormulaApplied_471, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_473 = let Input = FilteredRows_472 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_474 = GroupedData_473,",
                "    UnionPrepared_475 = JoinPrepared_474,",
                "    SelectedColumns_476 = UnionPrepared_475,",
                "    FormulaApplied_477 = SelectedColumns_476,",
                "    FilteredRows_478 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_477), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_477 else Table.SelectRows(FormulaApplied_477, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_479 = let Input = FilteredRows_478 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_480 = GroupedData_479,",
                "    UnionPrepared_481 = JoinPrepared_480,",
                "    SelectedColumns_482 = UnionPrepared_481,",
                "    FormulaApplied_483 = SelectedColumns_482,",
                "    FilteredRows_484 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_483), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_483 else Table.SelectRows(FormulaApplied_483, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_485 = let Input = FilteredRows_484 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_486 = GroupedData_485,",
                "    UnionPrepared_487 = JoinPrepared_486,",
                "    SelectedColumns_488 = UnionPrepared_487,",
                "    FormulaApplied_489 = SelectedColumns_488,",
                "    FilteredRows_490 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_489), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_489 else Table.SelectRows(FormulaApplied_489, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_491 = let Input = FilteredRows_490 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_492 = GroupedData_491,",
                "    UnionPrepared_493 = JoinPrepared_492,",
                "    SelectedColumns_494 = UnionPrepared_493,",
                "    FormulaApplied_495 = SelectedColumns_494,",
                "    FilteredRows_496 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_495), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_495 else Table.SelectRows(FormulaApplied_495, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_497 = let Input = FilteredRows_496 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_498 = GroupedData_497,",
                "    UnionPrepared_499 = JoinPrepared_498,",
                "    SelectedColumns_500 = UnionPrepared_499,",
                "    FormulaApplied_501 = SelectedColumns_500,",
                "    FilteredRows_502 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_501), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_501 else Table.SelectRows(FormulaApplied_501, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_503 = let Input = FilteredRows_502 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_504 = GroupedData_503,",
                "    UnionPrepared_505 = JoinPrepared_504,",
                "    SelectedColumns_506 = UnionPrepared_505,",
                "    FormulaApplied_507 = SelectedColumns_506,",
                "    FilteredRows_508 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_507), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_507 else Table.SelectRows(FormulaApplied_507, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_509 = let Input = FilteredRows_508 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_510 = GroupedData_509,",
                "    UnionPrepared_511 = JoinPrepared_510,",
                "    SelectedColumns_512 = UnionPrepared_511,",
                "    FormulaApplied_513 = SelectedColumns_512,",
                "    FilteredRows_514 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_513), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_513 else Table.SelectRows(FormulaApplied_513, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_515 = let Input = FilteredRows_514 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_516 = GroupedData_515,",
                "    UnionPrepared_517 = JoinPrepared_516,",
                "    SelectedColumns_518 = UnionPrepared_517,",
                "    FormulaApplied_519 = SelectedColumns_518,",
                "    FilteredRows_520 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_519), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_519 else Table.SelectRows(FormulaApplied_519, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_521 = let Input = FilteredRows_520 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_522 = GroupedData_521,",
                "    UnionPrepared_523 = JoinPrepared_522,",
                "    SelectedColumns_524 = UnionPrepared_523,",
                "    FormulaApplied_525 = SelectedColumns_524,",
                "    FilteredRows_526 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_525), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_525 else Table.SelectRows(FormulaApplied_525, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_527 = let Input = FilteredRows_526 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_528 = GroupedData_527,",
                "    UnionPrepared_529 = JoinPrepared_528,",
                "    SelectedColumns_530 = UnionPrepared_529,",
                "    FormulaApplied_531 = SelectedColumns_530,",
                "    FilteredRows_532 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_531), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_531 else Table.SelectRows(FormulaApplied_531, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_533 = let Input = FilteredRows_532 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_534 = GroupedData_533,",
                "    UnionPrepared_535 = JoinPrepared_534,",
                "    SelectedColumns_536 = UnionPrepared_535,",
                "    FormulaApplied_537 = SelectedColumns_536,",
                "    FilteredRows_538 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_537), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_537 else Table.SelectRows(FormulaApplied_537, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_539 = let Input = FilteredRows_538 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_540 = GroupedData_539,",
                "    UnionPrepared_541 = JoinPrepared_540,",
                "    SelectedColumns_542 = UnionPrepared_541,",
                "    FormulaApplied_543 = SelectedColumns_542,",
                "    FilteredRows_544 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_543), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_543 else Table.SelectRows(FormulaApplied_543, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_545 = let Input = FilteredRows_544 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_546 = GroupedData_545,",
                "    UnionPrepared_547 = JoinPrepared_546,",
                "    SelectedColumns_548 = UnionPrepared_547,",
                "    FormulaApplied_549 = SelectedColumns_548,",
                "    FilteredRows_550 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_549), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_549 else Table.SelectRows(FormulaApplied_549, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_551 = let Input = FilteredRows_550 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_552 = GroupedData_551,",
                "    UnionPrepared_553 = JoinPrepared_552,",
                "    SelectedColumns_554 = UnionPrepared_553,",
                "    FormulaApplied_555 = SelectedColumns_554,",
                "    FilteredRows_556 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_555), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_555 else Table.SelectRows(FormulaApplied_555, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_557 = let Input = FilteredRows_556 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_558 = GroupedData_557,",
                "    UnionPrepared_559 = JoinPrepared_558,",
                "    SelectedColumns_560 = UnionPrepared_559,",
                "    FormulaApplied_561 = SelectedColumns_560,",
                "    FilteredRows_562 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_561), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_561 else Table.SelectRows(FormulaApplied_561, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_563 = let Input = FilteredRows_562 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_564 = GroupedData_563,",
                "    UnionPrepared_565 = JoinPrepared_564,",
                "    SelectedColumns_566 = UnionPrepared_565,",
                "    FormulaApplied_567 = SelectedColumns_566,",
                "    FilteredRows_568 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_567), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_567 else Table.SelectRows(FormulaApplied_567, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_569 = let Input = FilteredRows_568 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_570 = GroupedData_569,",
                "    UnionPrepared_571 = JoinPrepared_570,",
                "    SelectedColumns_572 = UnionPrepared_571,",
                "    FormulaApplied_573 = SelectedColumns_572,",
                "    FilteredRows_574 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_573), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_573 else Table.SelectRows(FormulaApplied_573, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_575 = let Input = FilteredRows_574 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_576 = GroupedData_575,",
                "    UnionPrepared_577 = JoinPrepared_576,",
                "    SelectedColumns_578 = UnionPrepared_577,",
                "    FormulaApplied_579 = SelectedColumns_578,",
                "    FilteredRows_580 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_579), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_579 else Table.SelectRows(FormulaApplied_579, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_581 = let Input = FilteredRows_580 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_582 = GroupedData_581,",
                "    UnionPrepared_583 = JoinPrepared_582,",
                "    SelectedColumns_584 = UnionPrepared_583,",
                "    FormulaApplied_585 = SelectedColumns_584,",
                "    FilteredRows_586 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_585), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_585 else Table.SelectRows(FormulaApplied_585, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_587 = let Input = FilteredRows_586 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_588 = GroupedData_587,",
                "    UnionPrepared_589 = JoinPrepared_588,",
                "    SelectedColumns_590 = UnionPrepared_589,",
                "    FormulaApplied_591 = SelectedColumns_590,",
                "    FilteredRows_592 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_591), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_591 else Table.SelectRows(FormulaApplied_591, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_593 = let Input = FilteredRows_592 in Table.Group(Input, {}, {}),",
                "    JoinPrepared_594 = GroupedData_593,",
                "    UnionPrepared_595 = JoinPrepared_594,",
                "    SelectedColumns_596 = UnionPrepared_595,",
                "    FormulaApplied_597 = SelectedColumns_596,",
                "    FilteredRows_598 = let required = {\"MetricA\"}, existing = Table.ColumnNames(FormulaApplied_597), missing = List.Select(required, each not List.Contains(existing, _, Comparer.OrdinalIgnoreCase)) in if List.Count(missing) > 0 then FormulaApplied_597 else Table.SelectRows(FormulaApplied_597, each try ([MetricA] > 0) otherwise false),",
                "    GroupedData_599 = let Input = FilteredRows_598 in Table.Group(Input, {}, {}),",
                "    Checkpoint_600 = GroupedData_599",
                "in",
                "    Checkpoint_600),",
                "    __BimColumns = {\"MetricA\"},",
                "    __SafeBase = try",
                "        __Source",
                "    otherwise",
                "        Table.FromRecords({{}}, __BimColumns),",
                "    __ExistingColumns = Table.ColumnNames(__SafeBase),",
                "    __MissingColumns = List.Select(__BimColumns, each not List.Contains(__ExistingColumns, _, Comparer.OrdinalIgnoreCase)),",
                "    __WithMissingColumns = List.Accumulate(",
                "        __MissingColumns,",
                "        __SafeBase,",
                "        (tbl, col) => if Table.HasColumns(tbl, col) then tbl else Table.AddColumn(tbl, col, each null, type any)",
                "    ),",
                "    __FinalOutput = Table.SelectColumns(__WithMissingColumns, __BimColumns, MissingField.UseNull)",
                "in",
                "    __FinalOutput"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [],
    "expressions": [
      {
        "name": "DataSourcePath",
        "kind": "m",
        "expression": [
          "\"https://sorimtechnologies.sharepoint.com/large_fact_100k.csv\""
        ],
        "annotations": [
          {
            "name": "IsParameterQuery",
            "value": "True"
          },
          {
            "name": "IsParameterQueryRequired",
            "value": "False"
          },
          {
            "name": "PBI_QueryOrder",
            "value": "0"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.130.930.0"
      },
      {
        "name": "createdBy",
        "value": "QlikAI_Accelerator"
      }
    ]
  }
}
