{
  "name": "Standered_macro_parent",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "customer_master_500k_raw",
        "columns": [
          {
            "name": "CustomerID",
            "dataType": "string",
            "sourceColumn": "CustomerID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CustomerName",
            "dataType": "string",
            "sourceColumn": "CustomerName",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Country",
            "dataType": "string",
            "sourceColumn": "Country",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "customer_master_500k_raw-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    __Source = (let",
                "    Source = SharePoint.Files(\"https://sorimtechnologies.sharepoint.com\", [ApiVersion = 15]),",
                "    MatchingFiles = Table.SelectRows(Source, each [Name] = \"customer_master_500k.csv\"),",
                "    FileContent = if Table.RowCount(MatchingFiles) = 0 then error \"File not found in SharePoint: customer_master_500k.csv\" else MatchingFiles{0}[Content],",
                "    CsvData = Csv.Document(FileContent, [Delimiter = \",\", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(CsvData, [PromoteAllScalars = true]),",
                "    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, List.Transform(Table.ColumnNames(PromotedHeaders), each {_, type text}))",
                "in",
                "    ChangedTypes),",
                "    __BimColumns = {\"CustomerID\", \"CustomerName\", \"Country\"},",
                "    __SafeBase = try",
                "        __Source",
                "    otherwise",
                "        Table.FromRecords({{}}, __BimColumns),",
                "    __ExistingColumns = Table.ColumnNames(__SafeBase),",
                "    __MissingColumns = List.Select(__BimColumns, each not List.Contains(__ExistingColumns, _, Comparer.OrdinalIgnoreCase)),",
                "    __WithMissingColumns = List.Accumulate(",
                "        __MissingColumns,",
                "        __SafeBase,",
                "        (tbl, col) => if Table.HasColumns(tbl, col) then tbl else Table.AddColumn(tbl, col, each null, type any)",
                "    ),",
                "    __FinalOutput = Table.SelectColumns(__WithMissingColumns, __BimColumns, MissingField.UseNull)",
                "in",
                "    __FinalOutput"
              ]
            }
          }
        ]
      },
      {
        "name": "product_catalog_100k_raw",
        "columns": [
          {
            "name": "Product",
            "dataType": "string",
            "sourceColumn": "Product",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Price",
            "dataType": "string",
            "sourceColumn": "Price",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "product_catalog_100k_raw-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    __Source = (let",
                "    Source = SharePoint.Files(\"https://sorimtechnologies.sharepoint.com\", [ApiVersion = 15]),",
                "    MatchingFiles = Table.SelectRows(Source, each [Name] = \"product_catalog_100k.csv\"),",
                "    FileContent = if Table.RowCount(MatchingFiles) = 0 then error \"File not found in SharePoint: product_catalog_100k.csv\" else MatchingFiles{0}[Content],",
                "    CsvData = Csv.Document(FileContent, [Delimiter = \",\", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(CsvData, [PromoteAllScalars = true]),",
                "    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, List.Transform(Table.ColumnNames(PromotedHeaders), each {_, type text}))",
                "in",
                "    ChangedTypes),",
                "    __BimColumns = {\"Product\", \"Category\", \"Price\"},",
                "    __SafeBase = try",
                "        __Source",
                "    otherwise",
                "        Table.FromRecords({{}}, __BimColumns),",
                "    __ExistingColumns = Table.ColumnNames(__SafeBase),",
                "    __MissingColumns = List.Select(__BimColumns, each not List.Contains(__ExistingColumns, _, Comparer.OrdinalIgnoreCase)),",
                "    __WithMissingColumns = List.Accumulate(",
                "        __MissingColumns,",
                "        __SafeBase,",
                "        (tbl, col) => if Table.HasColumns(tbl, col) then tbl else Table.AddColumn(tbl, col, each null, type any)",
                "    ),",
                "    __FinalOutput = Table.SelectColumns(__WithMissingColumns, __BimColumns, MissingField.UseNull)",
                "in",
                "    __FinalOutput"
              ]
            }
          }
        ]
      },
      {
        "name": "sales_transactions_2023_raw",
        "columns": [
          {
            "name": "CustomerID",
            "dataType": "string",
            "sourceColumn": "CustomerID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sales",
            "dataType": "string",
            "sourceColumn": "Sales",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product",
            "dataType": "string",
            "sourceColumn": "Product",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "OrderDate",
            "dataType": "string",
            "sourceColumn": "OrderDate",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "sales_transactions_2023_raw-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    __Source = (let",
                "    Source = SharePoint.Files(\"https://sorimtechnologies.sharepoint.com\", [ApiVersion = 15]),",
                "    MatchingFiles = Table.SelectRows(Source, each [Name] = \"sales_transactions_2023.csv\"),",
                "    FileContent = if Table.RowCount(MatchingFiles) = 0 then error \"File not found in SharePoint: sales_transactions_2023.csv\" else MatchingFiles{0}[Content],",
                "    CsvData = Csv.Document(FileContent, [Delimiter = \",\", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(CsvData, [PromoteAllScalars = true]),",
                "    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, List.Transform(Table.ColumnNames(PromotedHeaders), each {_, type text}))",
                "in",
                "    ChangedTypes),",
                "    __BimColumns = {\"CustomerID\", \"Region\", \"Sales\", \"Product\", \"OrderDate\"},",
                "    __SafeBase = try",
                "        __Source",
                "    otherwise",
                "        Table.FromRecords({{}}, __BimColumns),",
                "    __ExistingColumns = Table.ColumnNames(__SafeBase),",
                "    __MissingColumns = List.Select(__BimColumns, each not List.Contains(__ExistingColumns, _, Comparer.OrdinalIgnoreCase)),",
                "    __WithMissingColumns = List.Accumulate(",
                "        __MissingColumns,",
                "        __SafeBase,",
                "        (tbl, col) => if Table.HasColumns(tbl, col) then tbl else Table.AddColumn(tbl, col, each null, type any)",
                "    ),",
                "    __FinalOutput = Table.SelectColumns(__WithMissingColumns, __BimColumns, MissingField.UseNull)",
                "in",
                "    __FinalOutput"
              ]
            }
          }
        ]
      },
      {
        "name": "Standered_macro_parent",
        "columns": [],
        "partitions": [
          {
            "name": "Standered_macro_parent-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = SharePoint.Files(\"https://sorimtechnologies.sharepoint.com\", [ApiVersion = 15]),",
                "    MatchingFiles = Table.SelectRows(Source, each [Name] = \"customer_master_500k.csv\"),",
                "    FileContent = if Table.RowCount(MatchingFiles) = 0 then error \"File not found in SharePoint: customer_master_500k.csv\" else MatchingFiles{0}[Content],",
                "    CsvData = Csv.Document(FileContent, [Delimiter = \",\", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(CsvData, [PromoteAllScalars = true]),",
                "    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, List.Transform(Table.ColumnNames(PromotedHeaders), each {_, type text})),",
                "    ManualReview_1 = ChangedTypes,",
                "    Checkpoint_2 = ManualReview_1,",
                "    Checkpoint_3 = Checkpoint_2,",
                "    Checkpoint_4 = Checkpoint_3,",
                "    Checkpoint_5 = Checkpoint_4,",
                "    Checkpoint_6 = Checkpoint_5,",
                "    ManualReview_7 = Checkpoint_6",
                "in",
                "    ManualReview_7"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [],
    "expressions": [
      {
        "name": "DataSourcePath",
        "kind": "m",
        "expression": [
          "\"D:\\csvFiles\\complex_workflow_yxmdFiles\\alteryx_sample_dataset\\data\\customer_master_500k.csv\""
        ],
        "annotations": [
          {
            "name": "IsParameterQuery",
            "value": "True"
          },
          {
            "name": "IsParameterQueryRequired",
            "value": "False"
          },
          {
            "name": "PBI_QueryOrder",
            "value": "0"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.130.930.0"
      },
      {
        "name": "createdBy",
        "value": "QlikAI_Accelerator"
      }
    ]
  }
}